### ISSUE TITLE
Updating attribute buffer after creation

### ISSUE THREAD

**Issue by oparisy** [stackgl/gl-geometry#14]
There is currently no easy way in `gl-geometry` to update the content of the `gl-buffer` created when `attr()` is called.

A common use case for this is animating a mesh by regularly uploading new vertex positions to the GPU. Note that `gl-buffer` objects are already suited for this since they are created by default with the `gl.DYNAMIC_DRAW` usage, and they expose an `update()` function.

I think a way to update those buffers while preserving the ease of use of the current `gl-geometry` API would be to detect at the beginning of `attr()` if a previous call was already made for the provided `name` (as stored in `_keys`). If so, `normalize()` could be called with an extra attribute (the existing buffer, as found in `_attributes`) and would be in charge of finally calling the buffer `update()` function. This would provide an opportunity to factorize/re-use the numerous conversions existing in `normalize()`.

Hence after an initial `Geom(gl).attr().attr()....faces()`, extra `attr()` calls could be issued to update buffer contents as needed. No API change!

That being said, I am not very clear on why `faces()` can only be called after all of the `.attr()` calls (as per the documentation). Is this due to `_length` computation? Would the modification I suggest be influenced by this constraint? Let's also note that calling `update()` can change the length of a buffer (probably not a common use case though, since all attributes and the elements index must then be updated accordingly).

I would have preferred to directly write a PR for this instead of this draft, but as you can see design details are a little bit vague for me currently so I'd like to discuss this beforehand.

More importantly, is this a direction you're interested in seeing `gl-geometry` going to?

Regards,
Olivier.

**Comment by hughsk** [comment]
:100: for being able to update buffers, a PR would be wonderful :) Looking at the code again, I think you might be right that it's the length computation — that being said, it could be a simple matter of checking if `_index` already exists [here](https://github.com/hughsk/gl-geometry/blob/master/index.js#L93-L99)?

**Comment by oparisy** [comment]
The length issue is addressed in https://github.com/hughsk/gl-geometry/pull/15.

**Comment by hughsk** [comment]
:tada:

**Comment by oparisy** [comment]
Hum, may we reopen this? The attributes updating part is not done already, #15 was just a precondition :grinning:

**Comment by hughsk** [comment]
Oops! Reopening :)

**Comment by oparisy** [comment]
Are you OK with me adding some test assets I built for this feature (a model and its associated vertex animation data), and taking the opportunity to move test-related files into a `test` sub-folder?

**Comment by oparisy** [comment]
#16 fully addresses this issue.

**Comment by oparisy** [comment]
Closed since #16 has been merged and released.
